#!/usr/bin/env php
<?php

include 'api/api.php';

pcntl_async_signals(true);

\API\Autoloader::load_plugins();

pcntl_signal(SIGUSR1, function ($signal) {
    print("YOLO\n");
});

$wait = 60;
$next = 0;

for(;;)
{
    $stamp = time();
    do {
        if ($stamp >= $next) {break;}
        $diff = $next - $stamp;
        sleep($diff);
        $stamp = time();
    } while ($stamp < $next);

    \API\Autoloader::run_plugins();

    $next = $stamp + $wait;
    sleep($wait);
}