#!/usr/bin/env php
<?php

include 'api/api.php';
include 'api/common.php';

\API\Autoloader::load_plugins();

$wait = 5;
$next = 0;

for(;;)
{
    $stamp = time();
    do {
        if ($stamp >= $next) {break;}
        $diff = $next - $stamp;
        sleep($diff);
        $stamp = time();
    } while ($stamp < $next);

    __debug("Tick");

    \API\Autoloader::run_plugins();

    __debug("Tock");

    $next = $stamp + $wait;
    sleep($wait);
}